name: Weitao Wan
description: Weitao Wan's Homepage
menu:
 - page: Home
   url: /
 - page: Publications
   url: /publications
 - page: Research
   url: /research
menu_external:
 - title: Github
   url: "https://github.com/wanweitao"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: 
locale: zh_CN